#!/usr/bin/env node
/**
 * 🔍 MCP Web Search Server
 * Multi-engine web search via DuckDuckGo (no API key).
 */
import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const server=new Server({name:"mcp-server-web-search",version:"1.0.0"},{capabilities:{tools:{}}});
async function ddgSearch(query,max=10){const url=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;const resp=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; MCPBot/1.0)"}});if(!resp.ok)throw new Error(`Search failed:HTTP ${resp.status}`);const html=await resp.text();const results=[];const linkRegex=/<a[^>]*class="result__a"[^>]*href="([^"]+)"[^>]*>([^<]+)<\/a>/gi;const snipRegex=/<a[^>]*class="result__snippet"[^>]*>([^<]+(?:<[^>]+>[^<]*)*)<\/a>/gi;let m;const links=[];while((m=linkRegex.exec(html))!==null&&links.length<max){links.push({title:m[2].replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim(),url:m[1].replace(/&amp;/g,"&")})}const snips=[];while((m=snipRegex.exec(html))!==null){snips.push(m[1].replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").trim())}for(let i=0;i<Math.min(links.length,snips.length,max);i++){results.push({...links[i],snippet:snips[i]||""})}return results}
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"web_search",description:"Search the web using DuckDuckGo.",inputSchema:{type:"object",properties:{query:{type:"string",description:"Search query"},count:{type:"number",description:"Max results (1-20, default:10)"}},required:["query"]}},{name:"fetch_page",description:"Fetch text content from a webpage URL.",inputSchema:{type:"object",properties:{url:{type:"string",description:"Webpage URL"}},required:["url"]}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;switch(name){case"web_search":{const query=requireParam(args,"query");const count=Math.min(20,Math.max(1,Number(args?.count)||10));const results=await ddgSearch(query,count);if(!results.length)return success(`🔍 Search:"${query}"\n\nNo results found.`);const lines=[`🔍 Search Results for "${query}"\n`,`Found ${results.length} result(s):\n`];results.forEach((r,i)=>{lines.push(`[${i+1}] ${r.title}`);lines.push(`    🔗 ${r.url}`);if(r.snippet)lines.push(`    📝 ${r.snippet}`);lines.push("")});return success(lines.join("\n"))}
case"fetch_page":{const url=requireParam(args,"url");const resp=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; MCPBot/1.0)"}});if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const ct=resp.headers.get("content-type")||"";if(!ct.includes("text/html"))throw new Error(`Not HTML (${ct})`);let text=(await resp.text()).replace(/<script[^>]*>[\s\S]*?<\/script>/gi," ").replace(/<style[^>]*>[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&[a-z]+;/g," ").replace(/\s+/g," ").trim();if(text.length>5000)text=text.slice(0,5000)+`\n...(truncated)`;return success(`📄 Content from ${url}\n\n${text}`)}
default:return error(`Unknown tool:${name}`)}}catch(e){return error(e.message)}});
async function main(){const transport=new StdioServerTransport();await server.connect(transport);console.error("🔍 MCP Web Search Server running on stdio")}
main().catch(e=>{console.error("Fatal error:",e);process.exit(1)});