#!/usr/bin/env node
import*as fs from"node:fs";import*as path from"node:path";import*as os from"node:os";import{Server}from"@modelcontextprotocol/sdk/server/index.js";import{StdioServerTransport}from"@modelcontextprotocol/sdk/server/stdio.js";import{CallToolRequestSchema,ListToolsRequestSchema}from"@modelcontextprotocol/sdk/types.js";import{success,error,requireParam}from"@mcp-hub/shared";
const DB=process.env.MCP_MEMORY_PATH||path.join(os.homedir(),".mcp-memory.json");
const server=new Server({name:"mcp-server-memory",version:"1.0.0"},{capabilities:{tools:{}}});
function load(){try{if(fs.existsSync(DB))return JSON.parse(fs.readFileSync(DB,"utf-8"))}catch{}return{}}
function save(db){const d=path.dirname(DB);if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(DB,JSON.stringify(db,null,2))}
function ts(){return Math.floor(Date.now()/1000)}
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[{name:"memory_set",description:"Store a value with key. Supports TTL (seconds) and tags.",inputSchema:{type:"object",properties:{key:{type:"string",description:"Unique key"},value:{type:"string",description:"Value"},ttl:{type:"number",description:"TTL in seconds, 0=forever"},tags:{type:"string",description:"Comma-separated tags"}},required:["key","value"]}},{name:"memory_get",description:"Retrieve a value by key.",inputSchema:{type:"object",properties:{key:{type:"string"}},required:["key"]}},{name:"memory_delete",description:"Delete by key.",inputSchema:{type:"object",properties:{key:{type:"string"}},required:["key"]}},{name:"memory_list",description:"List entries, filter by tag or search.",inputSchema:{type:"object",properties:{tag:{type:"string"},search:{type:"string"}}}},{name:"memory_tags",description:"List all used tags.",inputSchema:{type:"object",properties:{}}}]}));
server.setRequestHandler(CallToolRequestSchema,async(request)=>{try{const{name,arguments:args}=request.params;const db=load();switch(name){case"memory_set":{const k=requireParam(args,"key");const v=requireParam(args,"value");const ttl=Number(args?.ttl)||0;const tags=(args?.tags||"").split(",").map(t=>t.trim()).filter(Boolean);const t=ts();const old=db[k];db[k]={key:k,value:v,tags,ttl,createdAt:old?.createdAt||t,updatedAt:t};save(db);return success("🧠 Stored: "+k+"\n📝 "+v.slice(0,200)+(v.length>200?"...":"")+"\n⏱️ TTL: "+(ttl?ttl+"s":"forever")+"\n🏷️ Tags: "+(tags.join(", ")||"none"))}
case"memory_get":{const k=requireParam(args,"key");const e=db[k];if(!e)return success("🔍 Not found: "+k);const t=ts();if(e.ttl>0&&(e.createdAt+e.ttl)<t){delete db[k];save(db);return success("⏰ Expired: "+k)}return success("🧠 "+k+"\n📝 "+e.value+"\n📅 Created: "+new Date(e.createdAt*1000).toISOString()+"\n⏱️ TTL: "+(e.ttl?e.ttl+"s":"forever")+"\n🏷️ "+(e.tags.join(", ")||"none"))}
case"memory_delete":{const k=requireParam(args,"key");const ok=!!db[k];delete db[k];save(db);return success(ok?"🗑️ Deleted: "+k:"🔍 Not found: "+k)}
case"memory_list":{const tag=(args?.tag||"").toLowerCase();const q=(args?.search||"").toLowerCase();let entries=Object.values(db).filter((e:any)=>!(e.ttl>0&&(e.createdAt+e.ttl)<ts()));if(tag)entries=entries.filter((e:any)=>e.tags.some((t:string)=>t.toLowerCase()===tag));if(q)entries=entries.filter((e:any)=>e.key.toLowerCase().includes(q)||e.value.toLowerCase().includes(q));entries.sort((a:any,b:any)=>b.updatedAt-a.updatedAt);const lines=["🧠 Memory ("+entries.length+" entries)"+(tag?" ["+tag+"]":"")+(q?" search:'"+q+"'":""),""];entries.slice(0,50).forEach((e:any,i)=>{lines.push((i+1)+". "+e.key+(e.tags.length?" ["+e.tags.join(", ")+"]":""));lines.push("   "+e.value.slice(0,100)+(e.value.length>100?"...":""))});if(entries.length>50)lines.push("... and "+(entries.length-50)+" more");return success(lines.join("\n"))}
case"memory_tags":{const db2=load();const tagSet=new Set<string>();Object.values(db2).forEach((e:any)=>{if(!(e.ttl>0&&(e.createdAt+e.ttl)<ts()))e.tags.forEach((t:string)=>tagSet.add(t))});const tags=Array.from(tagSet).sort();return success("🏷️ Tags ("+tags.length+"):\n"+tags.map(t=>"  #"+t).join("\n")||"  (no tags)")}
default:return error("Unknown: "+name)}}catch(e:any){return error(e.message)}});
async function main(){const t=new StdioServerTransport();await server.connect(t);console.error("🧠 Memory Server running ("+DB+")")}
main().catch(e=>{console.error(e);process.exit(1)});